In [230]:
import stl.mesh
import numpy
import trimesh
import random
import itertools

import meshutil
import meshgen
import examples
import cage

import importlib
importlib.reload(examples)

<module 'examples' from '/home/hodapp/dev/automata_scratch/examples.py'>

In [231]:
importlib.reload(cage)
c = cage.Cage.from_arrays([[0,0,0], [1,1,1]], [[2,2,2]])
c.splits

[0, 2]

In [232]:
c.verts[1:-1,:]

array([[1., 1., 1.]])

In [233]:
for i in c.polys():
    print(i)

[[0. 0. 0.]
 [1. 1. 1.]]
[[2. 2. 2.]]


In [234]:
center = meshutil.Transform().translate(-0.5, -0.5, 0)
cage0 = cage.Cage.from_arrays([
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
])#.transform(center)

In [235]:
cs,_,_ = cage0.subdivide_deprecated()
c1,c2,c3,c4 = cs

In [236]:
c1.verts

array([[0. , 0. , 0. ],
       [0.5, 0. , 0. ],
       [0.5, 0.5, 0. ],
       [0. , 0.5, 0. ]])

In [237]:
c2.verts

array([[0.5, 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0.5, 0. ],
       [0.5, 0.5, 0. ]])

In [238]:
c3.verts

array([[0.5, 0.5, 0. ],
       [1. , 0.5, 0. ],
       [1. , 1. , 0. ],
       [0.5, 1. , 0. ]])

In [239]:
c4.verts

array([[0. , 0.5, 0. ],
       [0.5, 0.5, 0. ],
       [0.5, 1. , 0. ],
       [0. , 1. , 0. ]])

In [240]:
overlap = cage0.classify_overlap(cs)
overlap

[array([3, 1, 2, 1], dtype=uint8),
 array([1, 3, 1, 2], dtype=uint8),
 array([2, 1, 3, 1], dtype=uint8),
 array([1, 2, 1, 3], dtype=uint8)]

In [241]:
# Pretty-print a little:
for i,(c,ols) in enumerate(zip(cs, overlap)):
    print("Cage {}:".format(i))
    for j,(vert,ol) in enumerate(zip(c.verts, ols)):
        print("    Vertex {}: type={} for position {}".format(j, ol, vert))

Cage 0:
    Vertex 0: type=3 for position [0. 0. 0.]
    Vertex 1: type=1 for position [0.5 0.  0. ]
    Vertex 2: type=2 for position [0.5 0.5 0. ]
    Vertex 3: type=1 for position [0.  0.5 0. ]
Cage 1:
    Vertex 0: type=1 for position [0.5 0.  0. ]
    Vertex 1: type=3 for position [1. 0. 0.]
    Vertex 2: type=1 for position [1.  0.5 0. ]
    Vertex 3: type=2 for position [0.5 0.5 0. ]
Cage 2:
    Vertex 0: type=2 for position [0.5 0.5 0. ]
    Vertex 1: type=1 for position [1.  0.5 0. ]
    Vertex 2: type=3 for position [1. 1. 0.]
    Vertex 3: type=1 for position [0.5 1.  0. ]
Cage 3:
    Vertex 0: type=1 for position [0.  0.5 0. ]
    Vertex 1: type=2 for position [0.5 0.5 0. ]
    Vertex 2: type=1 for position [0.5 1.  0. ]
    Vertex 3: type=3 for position [0. 1. 0.]


In [242]:
cf = cage.CageFork(None,
                   numpy.array([[0, 0, 0], [0.5, 0, 0], [1, 0, 0], [1, 0.5, 0],
                                [1, 1, 0], [0.5, 1, 0], [0, 1, 0], [0, 0.5, 0]]) + [0, 0, 2],
                   [[7, 0, 1], [1, 2, 3], [3, 4, 5], [5, 6, 7]]
                  )
mesh2 = cf.transition_from(cage0)

DEBUG: Transition from [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [0. 1. 0.]] to [[0.  0.  2. ]
 [0.5 0.  2. ]
 [1.  0.  2. ]
 [1.  0.5 2. ]
 [1.  1.  2. ]
 [0.5 1.  2. ]
 [0.  1.  2. ]
 [0.  0.5 2. ]]


In [243]:
import cProfile, pstats

In [244]:
#mesh = examples.ram_horn()
#mesh = examples.twist()
#mesh = examples.twist_nonlinear()
#mesh = examples.twist_from_gen()
#mesh = examples.twisty_torus(1000)
#mesh = examples.ram_horn2()
#mesh = examples.branch_test()
mesh = examples.ram_horn_branch()

DEBUG: Transition from [[-0.12779038  0.21102174  2.40470962]
 [ 0.33806165  0.70938821  2.14156165]
 [-0.16030482  0.91209228  1.64319518]
 [-0.62615685  0.41372581  1.90634315]] to [[-0.2626621   0.77854269  2.8165879 ]
 [-0.12337756  1.0097311   2.62782244]
 [ 0.01590698  1.24091952  2.43905698]
 [-0.21528143  1.19143859  2.20786857]
 [-0.44646984  1.14195767  1.97668016]
 [-0.58575438  0.91076926  2.16544562]
 [-0.72503892  0.67958085  2.35421108]
 [-0.49385051  0.72906177  2.58539949]]
DEBUG: Transition from [[-0.74347748  0.58794149  3.71597464]
 [-0.79727882  0.82750482  3.5970103 ]
 [-0.90111397  0.6973509   3.38269929]
 [-0.84731263  0.45778757  3.50166363]] to [[-1.21682916  0.70882435  3.91083553]
 [-1.24891256  0.79437337  3.82882192]
 [-1.28099597  0.87992239  3.7468083 ]
 [-1.28427431  0.79385876  3.65911734]
 [-1.28755265  0.70779513  3.57142638]
 [-1.25546925  0.62224611  3.65344   ]
 [-1.22338584  0.53669709  3.73545361]
 [-1.2201075   0.62276072  3.82314457]]
DEBUG: T

In [245]:
def gen_wave(freq=2.0, a=2.0, d_ph=0.05, count=80):
    ph = 0.0
    while True:
        xs = numpy.linspace(-10, 10, count)
        ys = numpy.zeros(count)
        zs = (numpy.sin(xs*freq + a*numpy.sin(ph)*numpy.pi) + 2)/2
        b1 = numpy.stack((xs,ys,zs), axis=-1)
        b2 = numpy.stack((xs,ys,zs - 2), axis=-1)
        yield [numpy.vstack((b1, b2[::-1,:]))]
        ph += d_ph

#gen = meshgen.gen_inc_y(gen_wave())
#mesh = meshgen.gen2mesh(gen, 200, False, False, True, True)
# The closing method in gen2mesh is inappropriate because
# my boundary is not convex!

In [246]:
def spiral3():
    b = numpy.array([
        [0, 0, 0],
        [1, 0, 0],
        [1, 0, 1],
        [0, 0, 1],
    ], dtype=numpy.float64) - [0.5, 0, 0.5]
    b *= 0.3
    b = meshutil.subdivide_boundary(b)
    b = meshutil.subdivide_boundary(b)
    bs = [b]
    # since it needs a generator:
    gen1 = itertools.repeat(bs)
    gen2 = meshgen.gen_twisted_boundary(gen1, ang=-0.2, dx0=0.5)
    gen3 = meshgen.gen_twisted_boundary(gen2, ang=0.07, dx0=1)
    gen4 = meshgen.gen_twisted_boundary(gen3, ang=-0.03, dx0=3)
    gen = meshgen.gen_inc_y(gen4, dy=0.1)
    mesh = meshgen.gen2mesh(
        gen, count=500, flip_order=True, close_first=True, close_last=True)
    return mesh

def profile():
    pr = cProfile.Profile()
    pr.enable()
    spiral3()
    pr.disable()
    ps = pstats.Stats(pr)
    return ps

#ps = profile()
#ps.sort_stats('tottime').print_stats()

In [247]:
# Work around some annoying-ass trimesh/threejs bug:
wtf = meshutil.Transform().scale(0.1).translate(15,0,0)
center = meshutil.Transform().translate(-0.5, -0.5, -0.5)
base = meshutil.cube(open_xz=False).transform(center)
base = base.transform(wtf)
mesh_out = mesh
# to enable:
#mesh_out = mesh_out.concat(base)

mesh_fname = "branch.stl"
mesh_out.to_stl_mesh().save(mesh_fname)

In [248]:
m = trimesh.Trimesh(vertices=mesh_out.v, faces=mesh_out.f)
# Also acceptable:
#m = trimesh.load_mesh(mesh_fname)

#m.show()
scene = trimesh.Scene([m])
scene.show()